# Generated by Django 4.1.13 on 2024-03-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('photo', models.ImageField(upload_to='agents/')),
                ('about', models.CharField(max_length=500)),
            ],
        ),
    ]
