# Generated by Django 4.1.13 on 2024-03-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aminitie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Balcony', 'Balcony'), ("Children's Playground", "Children's Playground"), ('Deck', 'Deck'), ('Elevator', 'Elevator'), ('Fitness Center', 'Fitness Center'), ('Garden', 'Garden'), ('Hot Tub', 'Hot Tub'), ('Modern Interior Design', 'Modern Interior Design'), ('Outdoor Kitchen', 'Outdoor Kitchen'), ('Parking Space', 'Parking Space'), ('Rooftop Terrace', 'Rooftop Terrace'), ('Solar Panels', 'Solar Panels'), ('Spa', 'Spa'), ('Sports Court', 'Sports Court'), ('Surveillance System', 'Surveillance System'), ('Swimming Pool', 'Swimming Pool')], default='Balcony', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='floor_plans/')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rent', 'Rent'), ('Sell', 'Sell')], default='Sell', max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Property Status',
                'verbose_name_plural': 'Property Status',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Apartment', 'Apartment'), ('Condominium', 'Condominium'), ('G+1 House', 'G+1 House'), ('G+2 House', 'G+2 House'), ('Mansion', 'Mansion'), ('Villa', 'Villa')], default='Apartment', max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'Property Type',
                'verbose_name_plural': 'Property Types',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('area', models.FloatField(help_text='Enter the area of the property in square meters.')),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('agent', models.ManyToManyField(to='realtors.agent')),
                ('aminitie', models.ManyToManyField(to='listings.aminitie')),
                ('floor_plans', models.ManyToManyField(to='listings.floorplan')),
                ('photos', models.ManyToManyField(to='listings.photo')),
                ('property_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.type')),
                ('propery_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.status')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
