# Generated by Django 4.1.13 on 2024-03-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Property Status', 'verbose_name_plural': 'Property Status'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': 'Property Type', 'verbose_name_plural': 'Property Types'},
        ),
    ]
